// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbnDVEZAUuv2Z2d3qrWN_IIgu-tu26jxo',
    appId: '1:554922277176:web:edfd9d3731ed347e5c29cd',
    messagingSenderId: '554922277176',
    projectId: 'sample-d7987',
    authDomain: 'sample-d7987.firebaseapp.com',
    databaseURL: 'https://sample-d7987-default-rtdb.firebaseio.com',
    storageBucket: 'sample-d7987.appspot.com',
    measurementId: 'G-MHY3C6SW58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvXnA0q7voWewQIX5Rd3_eNjzvWhJAzm0',
    appId: '1:554922277176:android:3d1d8801d62fa81e5c29cd',
    messagingSenderId: '554922277176',
    projectId: 'sample-d7987',
    databaseURL: 'https://sample-d7987-default-rtdb.firebaseio.com',
    storageBucket: 'sample-d7987.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvGmzQbk-qHURRj2kU04uhYSwZUMYxhZc',
    appId: '1:554922277176:ios:cfefe18887f611925c29cd',
    messagingSenderId: '554922277176',
    projectId: 'sample-d7987',
    databaseURL: 'https://sample-d7987-default-rtdb.firebaseio.com',
    storageBucket: 'sample-d7987.appspot.com',
    androidClientId: '554922277176-fa8dn513plshmkecnnvuud1kgcbc315b.apps.googleusercontent.com',
    iosBundleId: 'com.example.pizzaOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvGmzQbk-qHURRj2kU04uhYSwZUMYxhZc',
    appId: '1:554922277176:ios:b6b5c097975b92665c29cd',
    messagingSenderId: '554922277176',
    projectId: 'sample-d7987',
    databaseURL: 'https://sample-d7987-default-rtdb.firebaseio.com',
    storageBucket: 'sample-d7987.appspot.com',
    androidClientId: '554922277176-fa8dn513plshmkecnnvuud1kgcbc315b.apps.googleusercontent.com',
    iosBundleId: 'com.example.pizzaOrderApp.RunnerTests',
  );
}
